common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: roflmail
  password: roflmail
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *common
  database: roflmail_development

test:
  <<: *common
  database: roflmail_test

production:
  <<: *common
  database: roflmail_production
